# Generated by Django 3.1.7 on 2021-06-09 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_group_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffworkerpayment',
            name='payment_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_worker_payment', to='staff_group_payments.staffworkerpaymentgroup'),
        ),
    ]
